### ISSUE TITLE
unable to load certificate

### ISSUE THREAD

**Issue by osrufung** [commandtab/ios-fingerprinter#2]
Provisioning profile contains 1 developer certificates:
unable to load certificate
8746:error:0906D066:PEM routines:PEM_read_bio:bad end line:/SourceCache/OpenSSL098/OpenSSL098-52.20.2/src/crypto/pem/pem_lib.c:747:

I've updated my shell script with your changes, but... It fails again :(

**Comment by command-tab** [comment]
Hmm, which version of OS X are you on?

I saw that particular error when I was making the changes and hadn't yet put the `-----END CERTIFICATE-----` line on the last line, making the line endings not match what openssl wants.

**Comment by osrufung** [comment]
OS X 10.10.3 
OpenSSL 0.9.8zd 8 Jan 2015

That's the output, including a piece of the certificate info.

![screen shot 2015-05-14 at 08 10 48](https://cloud.githubusercontent.com/assets/583458/7626946/49fb4e2a-fa11-11e4-8474-8e597d26771f.png)

**Comment by osrufung** [comment]
This error was a exceptional case. It's working with current provisioning files generated in the iOS Dev Center :)
